const studentsData = [
  {
    id: 1,
    name: '12345',
    ticketNumber: 'A123',
    ticketTopic: 'React',
    examGrade: 4,
    ratingGrade: 5,
    comments: 'Good work',
  },
  {
    id: 2,
    name: '67910',
    ticketNumber: 'B456',
    ticketTopic: 'Angular',
    examGrade: 3,
    ratingGrade: 4,
    comments: 'Needs improvement',
  },
  {
    id: 3,
    name: '11121',
    ticketNumber: 'C789',
    ticketTopic: 'Vue',
    examGrade: 5,
    ratingGrade: 4,
    comments: 'Well done',
  },
  {
    id: 4,
    name: '16171',
    ticketNumber: 'D012',
    ticketTopic: 'React',
    examGrade: 2,
    ratingGrade: 3,
    comments: 'Could do better',
  },
  {
    id: 5,
    name: '81920',
    ticketNumber: 'E345',
    ticketTopic: 'Angular',
    examGrade: 4,
    ratingGrade: 5,
    comments: 'Excellent work',
  },
  {
    id: 6,
    name: '21223',
    ticketNumber: 'F678',
    ticketTopic: 'Vue',
    examGrade: 3,
    ratingGrade: 4,
    comments: 'Good effort',
  },
  {
    id: 7,
    name: '32425',
    ticketNumber: 'G901',
    ticketTopic: 'React',
    examGrade: 5,
    ratingGrade: 3,
    comments: 'Impressive work',
  },
  {
    id: 8,
    name: '42627',
    ticketNumber: 'H234',
    ticketTopic: 'Angular',
    examGrade: 4,
    ratingGrade: 4,
    comments: 'Well done',
  },
  {
    id: 9,
    name: '52829',
    ticketNumber: 'I567',
    ticketTopic: 'Vue',
    examGrade: 3,
    ratingGrade: 2,
    comments: 'Needs improvement',
  },
  {
    id: 10,
    name: '63031',
    ticketNumber: 'J890',
    ticketTopic: 'React',
    examGrade: 5,
    ratingGrade: 4,
    comments: 'Good job',
  },
  {
    id: 11,
    name: '73233',
    ticketNumber: 'K123',
    ticketTopic: 'Angular',
    examGrade: 2,
    ratingGrade: 3,
    comments: 'Could do better',
  },
  {
    id: 12,
    name: '83435',
    ticketNumber: 'L456',
    ticketTopic: 'Vue',
    examGrade: 4,
    ratingGrade: 5,
    comments: 'Excellent work',
  },
];

export default studentsData;
